# Generated by Django 4.2.15 on 2024-08-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMainOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('modeOfPayment', models.CharField(default='Cash', max_length=15)),
                ('customerFullName', models.CharField(blank=True, default='Default Customer', max_length=50)),
                ('customerPhoneNumber', models.CharField(blank=True, default='0000000000', max_length=10)),
                ('grandTotal', models.FloatField(default=0.0, max_length=10)),
                ('orderNumber', models.CharField(default='00000000000', editable=False, max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='Mango', max_length=100)),
                ('quantity', models.IntegerField()),
                ('mrp', models.FloatField(default=0.0, max_length=6)),
                ('sum', models.FloatField(default=0.0, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customerMainOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retailers.customermainorders')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_products', to='products.product')),
            ],
        ),
    ]
