# Generated by Django 4.2.15 on 2024-08-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process_batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(max_length=20)),
                ('expDate', models.DateField()),
                ('currentQuantity', models.FloatField(default=0.0, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_batch.batchmix')),
            ],
        ),
    ]
