# Generated by Django 4.2.15 on 2024-08-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=10)),
                ('base_version', models.CharField(blank=True, max_length=10, null=True)),
                ('force_update', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'update   ',
            },
        ),
        migrations.CreateModel(
            name='IphoneAppVersionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=10)),
                ('base_version', models.CharField(blank=True, max_length=10, null=True)),
                ('force_update', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customer IOS Version Number',
            },
        ),
        migrations.CreateModel(
            name='IphonePartnerAppVersionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=10)),
                ('base_version', models.CharField(blank=True, max_length=10, null=True)),
                ('force_update', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Partner IOS Version Number',
            },
        ),
        migrations.CreateModel(
            name='PartnerAppVersionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=10)),
                ('base_version', models.CharField(blank=True, max_length=10, null=True)),
                ('force_update', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Partner Android Version Number',
            },
        ),
    ]
