# Generated by Django 4.2 on 2024-10-01 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_units', models.PositiveIntegerField(default=0)),
                ('stock_lits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_stocks', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_nos', models.CharField(max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lit_factor', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('production_units', models.PositiveIntegerField(default=0)),
                ('production_lits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('production_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_units', models.PositiveIntegerField(default=0)),
                ('sales_lits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_stock_units', models.PositiveIntegerField(default=0)),
                ('closing_stock_lits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('units_per_crate', models.PositiveIntegerField(default=0)),
                ('physical_stock', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('opening_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='StockReport.openingstock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='stock_reports/')),
                ('is_editable', models.BooleanField(default=True)),
                ('stock_record', models.ManyToManyField(related_name='stock_records', to='StockReport.productstockrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stock_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
