# Generated by Django 4.2 on 2024-10-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockrecord',
            name='lit_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
