# Generated by Django 4.2 on 2024-10-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockReport', '0002_alter_productstockrecord_lit_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='user',
        ),
    ]
