# Generated by Django 4.2 on 2024-10-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockReport', '0003_remove_stockrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockrecord',
            name='volume_nos',
            field=models.IntegerField(default=0),
        ),
    ]
