# Generated by Django 4.2 on 2024-10-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockReport', '0004_alter_productstockrecord_volume_nos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockrecord',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
    ]
