# Generated by Django 4.2 on 2024-10-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockReport', '0005_alter_productstockrecord_mrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstockrecord',
            name='opening_stock',
        ),
        migrations.AddField(
            model_name='productstockrecord',
            name='opening_stock_lits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstockrecord',
            name='opening_stock_units',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OpeningStock',
        ),
    ]
