# Generated by Django 4.2 on 2024-10-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockReport', '0008_alter_productstockrecord_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='closing_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='opening_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='physical_stock',
            field=models.FloatField(default=0),
        ),
    ]
