# Generated by Django 4.2 on 2024-10-04 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockReport', '0011_productstockrecord_opening_stock_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when the product was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstockrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the product was last updated'),
        ),
    ]
