# Generated by Django 4.2 on 2024-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockReport', '0014_alter_stockrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockrecord',
            name='damage_in_units',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productstockrecord',
            name='return_in_units',
            field=models.FloatField(default=0.0),
        ),
    ]
