# Generated by Django 5.1 on 2024-08-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchmix',
            options={'verbose_name_plural': 'BatchMix'},
        ),
        migrations.AlterModelOptions(
            name='batchmixingredients',
            options={'verbose_name_plural': 'BatchMixIngredients'},
        ),
    ]
