# Generated by Django 5.1 on 2024-08-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('process_batch', '0002_alter_batchmix_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmixingredients',
            name='SyrupBatchMix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_mix_ingredients', to='process_batch.batchmix'),
        ),
        migrations.AlterField(
            model_name='batchmixingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_mix_ingredient', to='inventory.material'),
        ),
    ]
