# Generated by Django 4.2 on 2024-08-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0003_alter_batchmixingredients_syrupbatchmix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmix',
            name='batchCode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
