# Generated by Django 4.2 on 2024-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0004_alter_batchmix_batchcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmix',
            name='batchCode',
            field=models.CharField(max_length=100),
        ),
    ]
