# Generated by Django 4.2 on 2024-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0005_alter_batchmix_batchcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmixtemplate',
            name='batch_fat_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchmixtemplate',
            name='batch_snf_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchmixtemplate',
            name='butter_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchmixtemplate',
            name='cream_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchmixtemplate',
            name='milk_fat_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchmixtemplate',
            name='milk_snf_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchmixtemplate',
            name='smp_snf_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchmixtemplate',
            name='standard_converstion_factor',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
