# Generated by Django 4.2 on 2024-09-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0006_batchmixtemplate_batch_fat_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmixtemplate',
            name='batch_fat_percentage',
        ),
        migrations.RemoveField(
            model_name='batchmixtemplate',
            name='batch_snf_percentage',
        ),
        migrations.RemoveField(
            model_name='batchmixtemplate',
            name='butter_percentage',
        ),
        migrations.RemoveField(
            model_name='batchmixtemplate',
            name='cream_percentage',
        ),
        migrations.RemoveField(
            model_name='batchmixtemplate',
            name='milk_fat_percentage',
        ),
        migrations.RemoveField(
            model_name='batchmixtemplate',
            name='milk_snf_percentage',
        ),
        migrations.RemoveField(
            model_name='batchmixtemplate',
            name='smp_snf_percentage',
        ),
        migrations.RemoveField(
            model_name='batchmixtemplate',
            name='standard_converstion_factor',
        ),
    ]
