# Generated by Django 4.2 on 2024-09-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('process_batch', '0007_remove_batchmixtemplate_batch_fat_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMixIceCreamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.CharField(max_length=100)),
                ('batchCode', models.CharField(max_length=100)),
                ('expDays', models.CharField(max_length=10)),
                ('milk_fat_percentage', models.FloatField(default=0.0)),
                ('milk_snf_percentage', models.FloatField()),
                ('batch_fat_percentage', models.FloatField()),
                ('batch_snf_percentage', models.FloatField()),
                ('cream_percentage', models.FloatField()),
                ('butter_percentage', models.FloatField()),
                ('smp_snf_percentage', models.FloatField()),
                ('standard_converstion_factor', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_batch.batchmixsubcategory')),
            ],
            options={
                'verbose_name_plural': 'BatchMixIceCreamTemplateSyrupAndSauce',
            },
        ),
        migrations.CreateModel(
            name='BatchMixIceCreamTemplateIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('RMStore', 'RMStore'), ('ProcessStore', 'ProcessStore')], default='RMStore', max_length=20)),
                ('lowerLimit', models.FloatField(max_length=20)),
                ('percentage', models.FloatField(max_length=20)),
                ('upperLimit', models.FloatField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='process_batch.batchmixicecreamtemplate')),
            ],
            options={
                'verbose_name_plural': 'BatchMixTemplateIngredientsSyrupAndSauce',
            },
        ),
    ]
