# Generated by Django 4.2 on 2024-09-19 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_store', '0001_initial'),
        ('process_batch', '0009_alter_batchmixicecreamtemplate_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchmix',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchmixcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchmixicecreamtemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchmixicecreamtemplateingredients',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchmixingredients',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchmixsubcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchmixtemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchmixtemplateingredients',
            options={},
        ),
        migrations.AddField(
            model_name='batchmixingredients',
            name='ingredient_process_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_base_process_store', to='process_store.processstore'),
        ),
    ]
