# Generated by Django 4.2 on 2024-09-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0012_alter_batchmixingredients_ingredient_process_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmixingredients',
            name='ingredient_process_store',
        ),
    ]
