# Generated by Django 4.2 on 2024-09-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_store', '0001_initial'),
        ('process_batch', '0013_remove_batchmixingredients_ingredient_process_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmixingredients',
            name='ingredient_process_store',
            field=models.ManyToManyField(blank=True, null=True, to='process_store.processstore'),
        ),
    ]
