# Generated by Django 4.2 on 2024-09-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_goodsreturnnote_vendor_and_more'),
        ('process_batch', '0014_batchmixingredients_ingredient_process_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmixingredients',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_mix_ingredient', to='inventory.material'),
        ),
    ]
