# Generated by Django 4.2 on 2024-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_store', '0001_initial'),
        ('process_batch', '0016_alter_batchmixingredients_ingredient_process_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmixingredients',
            name='ingredient_process_store',
            field=models.ManyToManyField(related_name='batch_mix_ingredient_process', to='process_store.processstore'),
        ),
    ]
