# Generated by Django 4.2 on 2024-09-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0018_batchmixchocolateicecreamtemplate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchmixicecreamtemplate',
            options={'verbose_name_plural': 'BatchMixIceCreamTemplate'},
        ),
        migrations.AlterModelOptions(
            name='batchmixicecreamtemplateingredients',
            options={'verbose_name_plural': 'BatchMixIceCreamTemplateIngredients'},
        ),
    ]
