# Generated by Django 4.2 on 2024-10-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0019_alter_batchmixicecreamtemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateIceCreamMix',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('process_batch.batchmix',),
        ),
        migrations.CreateModel(
            name='IceCreamMix',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('process_batch.batchmix',),
        ),
        migrations.CreateModel(
            name='KulfiIceCreamMix',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('process_batch.batchmix',),
        ),
        migrations.CreateModel(
            name='SyrupAndSauce',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('process_batch.batchmix',),
        ),
    ]
