# Generated by Django 4.2 on 2024-10-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0020_chocolateicecreammix_icecreammix_kulfiicecreammix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chocolateicecreammix',
            options={'verbose_name': '3.Chocolate Ice Cream Mix Batch', 'verbose_name_plural': 'Chocolate Ice Cream Mix Batches'},
        ),
        migrations.AlterModelOptions(
            name='icecreammix',
            options={'verbose_name': '2.Ice Cream Mix Batch', 'verbose_name_plural': 'Ice Cream Mix Batches'},
        ),
        migrations.AlterModelOptions(
            name='kulfiicecreammix',
            options={'verbose_name': '4.Kulfi Ice Cream Mix Batch', 'verbose_name_plural': 'Kulfi Ice Cream Mix Batches'},
        ),
        migrations.AlterModelOptions(
            name='syrupandsauce',
            options={'verbose_name': '1.Syrup or Sauce Batch', 'verbose_name_plural': 'Syrup and Sauce Batches'},
        ),
    ]
