# Generated by Django 4.2 on 2024-10-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0021_alter_chocolateicecreammix_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KulfiIceCreamMix',
        ),
        migrations.CreateModel(
            name='KulfiIceCreamMix',
            fields=[
                ('batchmix_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process_batch.batchmix')),
            ],
            options={
                'verbose_name': '4.Kulfi Ice Cream Mix Batch',
                'verbose_name_plural': 'Kulfi Ice Cream Mix Batches',
            },
            bases=('process_batch.batchmix',),
        ),
    ]
