# Generated by Django 4.2 on 2024-10-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0022_delete_kulfiicecreammix_kulfiicecreammix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChocolateIceCreamMix',
        ),
        migrations.DeleteModel(
            name='IceCreamMix',
        ),
        migrations.DeleteModel(
            name='SyrupAndSauce',
        ),
    ]
