# Generated by Django 4.2 on 2024-10-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0023_delete_chocolateicecreammix_delete_icecreammix_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KulfiIceCreamMix',
        ),
    ]
