# Generated by Django 4.2 on 2024-10-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_store_typename'),
        ('process_store', '0001_initial'),
        ('process_batch', '0026_alter_batchmixingredients_ingredient_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmixingredients',
            name='ingredient_process_store',
        ),
        migrations.RemoveField(
            model_name='batchmixingredients',
            name='ingredient_store',
        ),
        migrations.AddField(
            model_name='batchmixingredients',
            name='ingredient_process_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_mix_ingredient_process', to='process_store.processstore'),
        ),
        migrations.AddField(
            model_name='batchmixingredients',
            name='ingredient_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_mix_ingredients', to='inventory.store'),
        ),
    ]
