# Generated by Django 4.2 on 2024-10-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0028_remove_batchmixingredients_ingredient_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmix',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
