# Generated by Django 4.2 on 2024-10-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0029_batchmix_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmix',
            name='is_expired',
        ),
    ]
