# Generated by Django 4.2 on 2024-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_batch', '0030_remove_batchmix_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmix',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
