# Generated by Django 4.2.15 on 2024-08-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerMainOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('mode_of_payment', models.CharField(default='Cash', max_length=15)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('order_by_factory', models.BooleanField(default=False)),
                ('CGST', models.FloatField(default=0.0, max_length=5)),
                ('SGST', models.FloatField(default=0.0, max_length=5)),
                ('IGST', models.FloatField(default=0.0, max_length=5)),
                ('gst', models.FloatField(default=0.0, max_length=5)),
                ('sub_total', models.FloatField(default=0.0, max_length=10)),
                ('grand_total', models.FloatField(default=0.0, max_length=10)),
                ('pending_amount', models.FloatField(default=0.0, max_length=10)),
                ('order_number', models.CharField(default='00000000000', editable=False, max_length=11)),
                ('CGST_rate', models.FloatField(default=0.0, max_length=5)),
                ('SGST_rate', models.FloatField(default=0.0, max_length=5)),
                ('IGST_rate', models.FloatField(default=0.0, max_length=5)),
                ('gst_rate', models.FloatField(default=0.0, max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Distributer_retailer', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetailerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Mango', max_length=100)),
                ('quantity', models.IntegerField()),
                ('distributor_margin_rate', models.FloatField(default=0.0, max_length=5)),
                ('distributor_margin_price', models.FloatField(default=0.0, max_length=10)),
                ('distributor_gst', models.FloatField(default=0.0, max_length=10)),
                ('distributor_sale', models.FloatField(default=0.0, max_length=10)),
                ('carton_size', models.IntegerField()),
                ('price_per_carton', models.FloatField()),
                ('mrp', models.FloatField(default=0.0, max_length=6)),
                ('sum', models.FloatField(default=0.0, max_length=10)),
                ('CGST', models.FloatField(default=0.0, max_length=5)),
                ('SGST', models.FloatField(default=0.0, max_length=5)),
                ('IGST', models.FloatField(default=0.0, max_length=5)),
                ('gst', models.FloatField(default=0.0, max_length=5)),
                ('amount', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('retailer_main_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailer_orders1', to='distributors.retailermainorders')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DistributerStock', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
