# Generated by Django 4.2 on 2024-10-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerorders',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
