# Generated by Django 5.1.2 on 2024-11-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertargetamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertargetamount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
