# Generated by Django 5.1.2 on 2024-11-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usertargetamount_achieved_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertargetamount',
            name='achieved_amount',
        ),
    ]
