# Generated by Django 4.2.15 on 2024-08-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReturnNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRNnumber', models.CharField(max_length=20)),
                ('mfgDate', models.DateField()),
                ('expDate', models.DateField()),
                ('billNo', models.CharField(max_length=40)),
                ('receivedDate', models.DateField(blank=True, null=True)),
                ('batchNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('grnMaterialDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('measure', models.CharField(choices=[('Ml', 'Ml'), ('Gm', 'Gm'), ('Kg', 'Kg'), ('Litre', 'Litre'), ('Tonnes', 'Tonnes')], default='Kg', max_length=10)),
                ('unitSize', models.FloatField(blank=True, max_length=10, null=True)),
                ('quantityPerPackage', models.IntegerField(blank=True, null=True)),
                ('unitPrice', models.FloatField(blank=True, max_length=10, null=True)),
                ('packageType', models.CharField(blank=True, max_length=50, null=True)),
                ('otherPackageType', models.CharField(blank=True, max_length=100, null=True)),
                ('totalQuantity', models.FloatField(blank=True, max_length=10, null=True)),
                ('totalPrice', models.FloatField(blank=True, max_length=10, null=True)),
                ('approvedQuantity', models.FloatField(blank=True, max_length=10, null=True)),
                ('approvedPrice', models.FloatField(blank=True, max_length=10, null=True)),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('damageSubject', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rejectedCompletely', models.BooleanField(default=False)),
                ('rejectedQuantity', models.FloatField(blank=True, max_length=10, null=True)),
                ('rejectedReason', models.TextField(blank=True, null=True)),
                ('rejectedImage1', models.ImageField(blank=True, null=True, upload_to='grn/rejectionImages/')),
                ('rejectedImage2', models.ImageField(blank=True, null=True, upload_to='grn/rejectionImages/')),
                ('rejectedImage3', models.ImageField(blank=True, null=True, upload_to='grn/rejectionImages/')),
                ('QCDateTime', models.DateTimeField(blank=True, null=True)),
                ('vehicleNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('damageImage1', models.ImageField(blank=True, null=True, upload_to='grn/')),
                ('damageImage2', models.ImageField(blank=True, null=True, upload_to='grn/')),
                ('damageImage3', models.ImageField(blank=True, null=True, upload_to='grn/')),
                ('invoiceImage', models.ImageField(blank=True, null=True, upload_to='grn/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GoodsReceivedNote',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(max_length=50)),
                ('materialDescription', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(choices=[('Ml', 'Ml'), ('Gm', 'Gm'), ('Kg', 'Kg'), ('Litre', 'Litre')], default='Kg', max_length=10)),
                ('totalQuantity', models.FloatField()),
                ('currentQuantity', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('materialName', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
            ],
            options={
                'verbose_name': 'Store',
            },
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTypeName', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorFullname', models.CharField(max_length=50)),
                ('enterpriseName', models.CharField(max_length=50)),
                ('vendorAddress', models.CharField(max_length=50)),
                ('vendorGSTno', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('enterpriseName', 'vendorGSTno')},
            },
        ),
        migrations.CreateModel(
            name='VendorContactPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VCPname', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='StoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentQuantity', models.FloatField()),
                ('ConsumedQuantity', models.FloatField()),
                ('RemainingQuantity', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('materialName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
            ],
        ),
        migrations.CreateModel(
            name='StoreGRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.goodsreturnnote')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='typeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.type'),
        ),
        migrations.CreateModel(
            name='SecurityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNo', models.CharField(max_length=20)),
                ('billNo', models.CharField(max_length=20)),
                ('invoiceImage', models.ImageField(blank=True, null=True, upload_to='media/static/invoiceImage/')),
                ('is_converted_to_grn', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='subType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.subtype'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.type'),
        ),
        migrations.AddField(
            model_name='goodsreturnnote',
            name='materialName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material'),
        ),
        migrations.AddField(
            model_name='goodsreturnnote',
            name='qualityCheckBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_check_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreturnnote',
            name='receivedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreturnnote',
            name='securityNote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.securitynote'),
        ),
        migrations.AddField(
            model_name='goodsreturnnote',
            name='typeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.type'),
        ),
        migrations.AddField(
            model_name='goodsreturnnote',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('materialName', 'typeName')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('materialName', 'type')},
        ),
    ]
