# Generated by Django 4.2 on 2024-09-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_material_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreturnnote',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_return_vendor', to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorcontactpersons',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactPersons', to='inventory.vendor'),
        ),
    ]
