# Generated by Django 4.2 on 2024-09-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_goodsreturnnote_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='typeName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.type'),
        ),
    ]
