# Generated by Django 4.2 on 2024-10-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_goodsreturnnote_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreturnnote',
            name='is_expired',
        ),
    ]
