# Generated by Django 4.2.15 on 2024-08-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.FloatField(default=0.0, max_length=5)),
                ('cgst', models.FloatField(default=0.0, max_length=5)),
                ('sgst', models.FloatField(default=0.0, max_length=5)),
                ('igst', models.FloatField(default=0.0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MainOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Verifying Payment', 'Verifying Payment'), ('Amount Paid', 'Amount Paid'), ('In Process', 'In Process'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Requested', max_length=30)),
                ('mode_of_payment', models.CharField(default='Cash', max_length=15)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('order_by_factory', models.BooleanField(default=False)),
                ('CGST', models.FloatField(default=0.0, max_length=5)),
                ('SGST', models.FloatField(default=0.0, max_length=5)),
                ('IGST', models.FloatField(default=0.0, max_length=5)),
                ('gst', models.FloatField(default=0.0, max_length=5)),
                ('sub_total', models.FloatField(default=0.0, max_length=10)),
                ('grand_total', models.FloatField(default=0.0, max_length=10)),
                ('order_number', models.CharField(default='00000000000', editable=False, max_length=11)),
                ('CGST_rate', models.FloatField(default=0.0, max_length=5)),
                ('SGST_rate', models.FloatField(default=0.0, max_length=5)),
                ('IGST_rate', models.FloatField(default=0.0, max_length=5)),
                ('gst_rate', models.FloatField(default=0.0, max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Distributer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Verifying Payment', 'Verifying Payment'), ('Amount Paid', 'Amount Paid'), ('In Process', 'In Process'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=30)),
                ('utrNo', models.CharField(blank=True, default='0', max_length=40, null=True)),
                ('cash', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('cheque', models.IntegerField(blank=True, default=0, null=True)),
                ('credit', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('updated_by', models.CharField(max_length=30)),
                ('updator_contact', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('main_order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Main_Order', to='orders.mainorders')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(default=0)),
                ('accepted_quantity', models.IntegerField(default=0)),
                ('factory_base_price', models.FloatField(default=0.0, max_length=10)),
                ('factory_gst_price', models.FloatField(default=0.0, max_length=10)),
                ('factory_sale', models.FloatField(default=0.0, max_length=10)),
                ('carton_size', models.IntegerField(default=0)),
                ('price_per_carton', models.FloatField(default=0.0, max_length=10)),
                ('mrp', models.FloatField(default=0.0, max_length=6)),
                ('discount', models.FloatField(default=0.0, max_length=5)),
                ('discount_amount', models.FloatField(default=0.0, max_length=10)),
                ('sum', models.FloatField(default=0.0, max_length=10)),
                ('CGST', models.FloatField(default=0.0, max_length=5)),
                ('SGST', models.FloatField(default=0.0, max_length=5)),
                ('IGST', models.FloatField(default=0.0, max_length=5)),
                ('gst', models.FloatField(default=0.0, max_length=5)),
                ('amount', models.FloatField(default=0.0)),
                ('main_order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Main_order', to='orders.mainorders')),
                ('product_name', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='Product_name', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryToCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=11)),
                ('order_date', models.DateField()),
                ('mode_of_payment', models.CharField(default='Cash', max_length=15)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('mrp', models.FloatField(default=0.0, max_length=6)),
                ('amount', models.FloatField(default=0.0)),
                ('product_name', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='Product_sold', to='products.product')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
