# Generated by Django 4.2.15 on 2024-08-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionFromSalesToDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionDistributor', to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionSales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='salesRetailerTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.FloatField(max_length=10)),
                ('mode_of_payment', models.CharField(default='Cash', max_length=20)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_distributor_transaction', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_retailer_transaction', to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_person_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='salesPersonCashInHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_in_hand', models.FloatField(default=0.0, max_length=10)),
                ('amount_transferred_to_distributer', models.FloatField(default=0.0, max_length=10)),
                ('total', models.FloatField(default=0.0, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_person_cash_in_hand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='retailerTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10)),
                ('totalSaleAmount', models.FloatField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_retailerTransactionDetails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'retailer Sale Details',
            },
        ),
        migrations.CreateModel(
            name='salesPersonordersTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_settled', models.FloatField(max_length=10)),
                ('pending_amount', models.FloatField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_main_orders_transaction', to='distributors.retailermainorders')),
                ('salesRetailerTransactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_person_retailer_transaction', to='sales.salesretailertransactions')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_person_orders_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sales_person', 'order')},
            },
        ),
        migrations.CreateModel(
            name='salesPerson_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_main_orders', to='distributors.retailermainorders')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_person_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sales_person', 'order')},
            },
        ),
        migrations.CreateModel(
            name='distributor_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_distributor', to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_sales_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'distributor_sales',
                'unique_together': {('sales_person', 'distributor')},
            },
        ),
    ]
