# Generated by Django 4.2 on 2024-10-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_product_discount', models.FloatField(max_length=50)),
                ('max_invoice_discount', models.FloatField(max_length=50)),
            ],
        ),
    ]
