# Generated by Django 4.2 on 2024-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
